### ISSUE TITLE
mDeBERTa for mReLiK?

### ISSUE THREAD

**Issue by zidsi** [SapienzaNLP/relik#1]
Thank you for sharing great work. Did you (or plan to) experiment with multilingual setup using e.g. mDeBERTa as base model? 

Additionaly can you elaborate on where metadata for EL is stored and how it's retrieved? In paper you state _We do not use any mention-entities dictionary to retrieve the list of possible entities to associate with a given mention._ but from first look into code I got impression that embeddings are used for looking up for "most simmilar" entities indexed. So one would still need embeddings based lookup (dictionary) for EL?

**Comment by edobobo** [comment]
Hey, you're welcome!

1. **We do plan to release a multilingual version of ReLiK** based, most probably, on mDeBERTa, but maybe even on some multilingual variant of the longformer architecture.
2. The metadata for EL are stored in an index containing both the embeddings of the entities and their respective metadata. So, in that sense we have a _dictionary_ containing for each entity its embedding. What we don't have, as instead many other EL systems do, is a dictionary containing for each mention all the entities that can be represented by that specific mention. Let me give you an example. Many EL systems need a dictionary, where for the mention "Michael", all the entities that can go under the name of "Michael" are listed (e.g. "Michael" -> "Michael_Jordan", "Michael_Jackson", ...). Not needing such a dictionary makes ReLiK way more flexible and easy to update with other entities. For a more in depth description of the work I suggest reading the paper!

**Comment by zidsi** [comment]
Thank you for clarification - looking forward to test multilingual version of ReLiK once released. mT5 for retriever base model should work just fine. I'll read the paper (and code) couple more times, to get ready 😀

However I still am conserned with real life app in mind. Storing milions of embeddings for (metadata/candidates ranking) EL index even at d=384 (using T5small instead of T5base) might require significant "dictionary" - e.g. |E| = 5.9M? Inverted EL pipeline is adaptable and solves mentions disambiguation if multiple entities share mention "wordform", for sure. Inverted (your) pipeline might even solve misspelled mentions where mentionform dict lookups would fail even for unambiguous entities. But increasing number of documents for GoldenRetriever (I like the name) will impact document_index.search performance. 

Did you benchmark EL pipeline performance WRT index size? Lowering k impact is well described in paper.

**Comment by LittlePea13** [comment]
Hi there @zidsi. 

We are aware of the memory concerns regarding the index. In the next update we are going to have some features in this regard. While the index for the EL config was used to allow for fair comparison with previous systems (such as entQA), you can also use a smaller index such as [relik-retriever-e5-base-v2-aida-blink-wikipedia-2Mpopular-index](https://huggingface.co/sapienzanlp/relik-retriever-e5-base-v2-aida-blink-wikipedia-2Mpopular-index) containing the most popular 2M entities in wikipedia.

We did not assess how reducing the index affects performance, as the set up would end up being quite different (i.e. if we keep all entities in AIDA and reduce the index by removing others, we give an unfair advantage to our system, and the contrary if we remove entities in AIDA). 

My suggestion is that if you know beforehand which entities you are interested in, you can trim your index by creating a documents.jsonl file with only the entities you need and then you can create your own index (see the CLI function create-index). Take into account that you can always store the index in the CPU which will take a small toll on the speed, but won't require that much GPU memory. And of course, stay tuned for next updates as we are looking at how to make the index more lightweight.
