### ISSUE TITLE
ValueError: `text` and `candidates` must have the same length.

### ISSUE THREAD

**Issue by MedSaidi11** [SapienzaNLP/relik#18]
Hello, when I try to execute this to test the reader :

candidates = ["Michael Jordan", "NBA", "Chicago Bulls", "Basketball", "United States"]
reader_span.read("Michael Jordan was one of the best players in the NBA.", candidates=candidates)

I received this error : 

ValueError: `text` and `candidates` must have the same length.

**Comment by LittlePea13** [comment]
Hi @MedSaidi11 could you show the rest of the code? 

I believe you are using directly the reader class, which read method doesn't work exactly like the one in the Readme. If you want to use relik without a retriever (i.e. you provide candidates), please follow the README and do:

```python
from relik import Relik
from relik.inference.data.objects import RelikOutput

# If you want to use only the reader
reader = Relik.from_pretrained("sapienzanlp/relik-entity-linking-large", retriever=None)
candidates = [
    "Michael Jordan",
    "National Basketball Association",
    "Walter Jordan",
    "Jordan",
    "50 Greatest Players in NBA History",
]
text = "Michael Jordan was one of the best players in the NBA."
relik_out: RelikOutput = reader(text, candidates=candidates)
```

You can specify your own reader if you want as well with:
```python
reader = Relik.from_pretrained("sapienzanlp/relik-entity-linking-large", retriever=None, reader="PereLluis13/relik-reader-deberta-large-wikipedia-aida-full-interleave-robust")
```

**Comment by MedSaidi11** [comment]
Yes exactly, thanks @LittlePea13 !
