### ISSUE TITLE
why did this error happen?

### ISSUE THREAD

**Issue by thealmight1** [SapienzaNLP/relik#20]
relik_out: RelikOutput = relik("Michael Jordan was one of the best players in the NBA.")
TypeError: 'DictConfig' object is not callable

**Comment by LittlePea13** [comment]
Hi @thealmight1, can you provide the whole script?

**Comment by thealmight1** [comment]
I manually downloaded the model which named "relik-entity-linking-large" from huggingface.co . the followings is my File structure:
    
<img width="206" alt="Snipaste_2024-10-03_09-02-10" src="https://github.com/user-attachments/assets/2e9829dc-e034-46a9-ab87-6e8155598849">
I changed the configuration files of these models,forcing them to use local model.
<img width="603" alt="Snipaste_2024-10-03_09-04-36" src="https://github.com/user-attachments/assets/f1514be0-0542-43ad-9ec7-ee7e5c7a14da">
Everything was going smoothly, but an error occurred when inputting text into the model.
<img width="633" alt="Snipaste_2024-10-03_09-12-30" src="https://github.com/user-attachments/assets/cc077530-a44f-430a-ad7c-563649919f94">
