### ISSUE TITLE
Loss Expression coherence

### ISSUE THREAD

**Issue by swissarthurfreeman** [SapienzaNLP/relik#27]
Dear All, 

We're studying your artefact as part of a master's thesis at the University of Geneva, I've been detailing and thinking about your loss functions for the reader's mention computation, however I think there may be a bug, which you'll likely be able to clear up for me as I'm 60% sure it's simply me not understanding something,

In the expressions for the losses, $`\mathcal{L}_S`$ and $`\mathcal{L}_E`$, I've found the first minus sign placement to be confusing. 
![image](https://github.com/user-attachments/assets/194e00b9-3ee2-4edd-a8f2-e293cac23245)

In equation $`\mathcal{L}_S`$ shouldn't the minus sign in the first equation be moved to the right of the sum, in order not to apply to the two terms ? 
And in equation $`\mathcal{L}_E`$ shouldn't the minus sign be right after the second sum, in front of the first indicator function ?

I came across this as I was trying to rewrite the losses without indicator functions for the sake of having an alternate form, 
![image](https://github.com/user-attachments/assets/3241f4c3-168e-48c0-8dcc-7e3004ed1c9b)

and the second equalities I established don't match the first due to the sign placement.

My logic for the first equation (which is similar with the second), is as follows : 

In the first equation, the logic behind the loss is clear, we want $`\mathds{P}_{Start}(s | X)`$ to be maximal since $s$ is in the ground truth, the log will be negative, since $`\mathds{P}_{Start}(s | X)`$ is a sigmoid output between [0, 1], a probability, the negative sign on the first sum turns it to positive, which if minimal, means $`\mathds{P}_{Start}(s | X)`$ was close to 1, which we want. In the second term, we want, (with $s$ a negative sample this time) $`\mathds{P}_{Start}(s | X)`$ to be minimal, e.g. close to 0, and if it isn't, it should yield a larger loss, which we don't want since we minimize $`\mathcal{L}`$. 

So to that end, $`1- \mathds{P}_{Start}(s | X)`$ should be as close as possible to 1, for the log to yield a sum of zeros, e.g. no error on negative samples. But if  $`1- \mathds{P}_{Start}(s | X)`$ is close to 0, this means the model incorrectly states a negative sample is the start of a mention, then the log of this combined with the -  will yield something close to $`+\infty`$, which will make the loss explode. 

So minimizing such an expression would encourage the model to correctly classify ground truth entity mention starts while discouraging it from incorrectly classifying negative samples as being start. 

Does it make sense or am I missing something ? 

Thanks in advance for any insights into this ! 

A. Freeman

**Comment by LittlePea13** [comment]
That's embarrassing. You are right, inner term shouldn't be a minus. That's what happens when you rewrite that stuff many times to fit well in the paper. In fact also L_rel suffers from the same typo. Thanks for bringing it up, will try to update at least in the arxiv version of the paper!

**Comment by swissarthurfreeman** [comment]
Dear @LittlePea13 , fantastic, thank you so much for the heads up ! Arthur
