### ISSUE TITLE
Docker deploy tips

### ISSUE THREAD

**Issue by zidsi** [SapienzaNLP/relik#5]
Besides probably docs missing step on how to pull cpu or gpu docker image and tagging it as _sapienzanlp/relik:latest_ to which docs reffer, I also suggest section/tip on mounting volume for HF ~/.cache/huggingface folder.

This way downloads of models and index can be reused between multiple config instances or failed attempts.

So far none of HF repo configs worked for me.

**Comment by Riccorl** [comment]
Thank you for the tips!

As you suggested, we’ve added more details about Docker images to the README, including instructions on how to mount a local HF cache folder.

We also updated the images on the hub, which should work now. Please let us know if you encounter any issues!

**Comment by zidsi** [comment]
It works like a charm with new docker image :)  I guess previous build had issues with passing provided params (e.g. --device cuda) and forced cpu no matter what and crashed (hence the cache volume I've done and suggested). Looks fixed now and FastAPI ReLiK is up and running. (fast ;)

To speed up docker instance startup one might want to:

-  *install spacy model 'en_core_web_sm'* at image build time

_[2024-08-06 14:23:35,886] [WARNING] [relik.load_spacy:63] [PID:8] [RANK:0] Spacy model 'en_core_web_sm' not found. Downloading and installing._

I'm not sure what the consequences are of missing *index.faiss for encoders* (e.g. _Couldn't download index.faiss from relik-ie/encoder-e5-base-v2-wikipedia-index, ignoring_) but if this means that Faiss index is build every time the fresh docker instance starts - it might be usefull to have option to store them on mounted volume as well. 

Not a huge hit as downloading e5-base-v2-wikipedia-index so feel free to close ticket with "won't do".

**Comment by Riccorl** [comment]
> To speed up docker instance startup one might want to:
> 
> - install spacy model 'en_core_web_sm' at image build time

We will definitely look into that for the next release, thanks for the suggestion!

> 'm not sure what the consequences are of missing index.faiss for encoders (e.g. Couldn't download index.faiss from relik-ie/encoder-e5-base-v2-wikipedia-index, ignoring) but if this means that Faiss index is build every time the fresh docker instance starts - it might be usefull to have option to store them on mounted volume as well.

We have both torch-based and faiss-based indices and we default to the former. The warning can be ignored (and will likely be removed in the next release), as ReLiK tries to download a set of predefined files from the Hub. Since you are downloading a torch-based index, you don’t need a faiss file, but it tries to download it anyway, hence the warning.
